CREATE TABLE bookmark
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    store_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_bookmark PRIMARY KEY (id)
);

CREATE TABLE review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    rating      FLOAT                                   NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE store
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_name   VARCHAR(255)                            NOT NULL,
    sido         VARCHAR(255),
    address      VARCHAR(255),
    category     VARCHAR(255),
    avg_rating   FLOAT,
    review_count INTEGER,
    CONSTRAINT pk_store PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255),
    role       VARCHAR(50)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE bookmark
    ADD CONSTRAINT FK_BOOKMARK_ON_STORE FOREIGN KEY (store_id) REFERENCES store (id);

ALTER TABLE bookmark
    ADD CONSTRAINT FK_BOOKMARK_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);